### ISSUE TITLE
"add_custom_fact" creates String-Facts instead of Symbol-Facts

### ISSUE THREAD

**Issue by cocker-cc** [voxpupuli/rspec-puppet-facts#142]
Hello,
I am using `rspec-puppet-facts 2.0.5` and `facterdb 1.19.0` on ruby `2.7.6` and `Puppet 7.19.0`.

When I try to add or override a Fact in my `spec_helper.rb` like so…:
```
add_custom_fact :blubb, 'blobb'
```
… then it appears in the Facts-Hash as String `"blubb" => "blobb"` instead of as a Symbol `:blubb => "blobb"`.

This leads to the Problem, that I cannot override Facts from Facter-DB, because f.e. `add_custom_fact :ipaddress => '1.2.3.4'` happens to create the String-Fact `"ipaddress" => '1.2.3.4'` besides the previously existing `:ipaddress => '10.0.2.15'` instead of overriding it.  The same goes for the nested Hash `:network` versus `"network"`.

Actually it seems to be even worse: 

My Rspec-Test throws…:  
```
expected that the catalogue would contain Service_monitoring::Monitor::Host[foo.example.com] 
with address set to "10.0.2.15" but it is set to "1.2.3.4"
```
… because the Rspec-Test picks up the Symbol-Fact…
```
        it 'should export itself as monitoring::host' do
          expect(exported_resources).to contain_service_monitoring__monitor__host(node)
            .with_address(facts[:networking]['ip'])
        end
```
… and the Puppet-Code picks up the String-Fact:
```
  $agent_ip_address                     = $::facts['networking']['ip']
```

I tried to find the Source of this Misbehaviour (IMHO), but even in [`rspec-puppet-facts.rb`](https://github.com/voxpupuli/rspec-puppet-facts/blob/master/lib/rspec-puppet-facts.rb#L196) the Symbols stay untouched:
```
  def add_custom_fact(name, value, options = {})
    options[:confine] = [options[:confine]] if options[:confine].is_a?(String)
    options[:exclude] = [options[:exclude]] if options[:exclude].is_a?(String)
    RspecPuppetFacts.register_custom_fact(name, value, options)
  end

  def self.register_custom_fact(name, value, options)
    @custom_facts ||= {}
    @custom_facts[name] = {:options => options, :value => value}
  end
```

So I guess either I need some Help about what I am doing wrong, or I spotted kind of a Bug.

**Comment by ekohl** [comment]
There's some additional messyness if you use `let(:node)` and IP addresses. https://github.com/puppetlabs/rspec-puppet/issues/15 is also open for that and I wonder if you're running into that now.
